# Generated by Django 5.1.1 on 2025-12-30 05:00

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture (max 5MB, 400x400px recommended)', null=True, upload_to=apps.users.models.user_profile_picture_path),
        ),
    ]
